---
- vars:
      env: prod
  vars_files: 
     - ["vars/{{env}}/main.yml"]
     - ["vars/{{env}}/vpc_info.yml"]
  hosts: local
  connection: local
  gather_facts: False
  tags: EC2 web instance provisioning
  roles:
    - role: ec2_web
