---
- name: Provision EC2 instances - zone 1
  local_action:
        module: ec2
        state: present
        id: "{{ aws_region }}.{{ aws_instanceType }}.{{ id_az1 }}"
        region: "{{ aws_region }}"
        keypair: "{{ aws_keypair }}"
        group:  "{{ security_group }}"
        instance_type: "{{ aws_instanceType }}"
        image: "{{ aws_image }}"
        count: "{{ count }}"
        vpc_subnet_id: "{{ vpc.subnets[0].id }}"
        assign_public_ip: True
        wait: yes
  register: ec2_instances_zone1

- name: Provision EC2 instances - zone 2
  local_action:
        module: ec2
        state: present
        id: "{{ aws_region }}.{{ aws_instanceType }}.{{ id_az2 }}"
        region: "{{ aws_region }}"
        keypair: "{{ aws_keypair }}"
        group: "{{ security_group }}"
        instance_type: "{{ aws_instanceType }}"
        image: "{{ aws_image }}"
        count: "{{ count }}"
        vpc_subnet_id: "{{ vpc.subnets[1].id }}"
        assign_public_ip: True
        wait: yes
  register: ec2_instances_zone2


- name: Add instance to local host group
  local_action: 'lineinfile dest=hosts regexp="{{ item.public_ip }}" insertafter="[webservers]" line="{{ item.public_ip }}"'
  with_items: ec2_instances_zone1.instances

- name: Add new zone 1 instances to host group
  local_action: add_host hostname="{{ item.public_ip }}" groupname=webservers
  with_items: ec2_instances_zone1.instances

- name: Add instance to local host group
  local_action: 'lineinfile dest=hosts regexp="{{ item.public_ip }}" insertafter="[webservers]" line="{{ item.public_ip }}"'
  with_items: ec2_instances_zone2.instances

- name: Add new zone 2 instances to host group
  local_action: add_host hostname="{{ item.public_ip }}" groupname=webservers 
  with_items: ec2_instances_zone2.instances

- name: Wait for SSH to come up
  local_action: wait_for 
                host={{ item.public_ip }}
                port=22 
                delay=15 
                timeout=320 
                state=started
  with_items: ec2_instances_zone1.instances

- name: Wait for SSH to come up
  local_action: wait_for
                host={{ item.public_ip }} 
                port=22
                delay=15 
                timeout=320 
                state=started
  with_items: ec2_instances_zone2.instances




- name: tag my launched instances
  ec2_tag: resource={{ item.id }} region="{{ aws_region }}" state=present
  with_items: ec2_instances_zone1.instances
  args:
    tags:
      Name: web

- name: tag my launched instances
  ec2_tag: resource={{ item.id }} region="{{ aws_region }}" state=present
  with_items: ec2_instances_zone2.instances
  args:
    tags:
      Name: web

