---
- name: "Provision VPC in 2 aws zones"
  local_action:
        module: ec2_vpc
        state: present
        cidr_block: 10.1.0.0/16
        resource_tags: '{"Name":"{{ vpc_name }}"}'
        subnets:
                - cidr: 10.1.1.0/24
                  az: "{{ aws_zone1 }}"
                  resource_tags: '{"Name":"{{ env }}_subnet_az1"}'
                - cidr: 10.1.2.0/24
                  az: "{{ aws_zone2 }}"
                  resource_tags: '{"Name":"{{ env }}_subnet_az2"}'
        internet_gateway: True
        route_tables:
                - subnets:
                        - 10.1.1.0/24
                        - 10.1.2.0/24
                  routes:
                        - dest: 0.0.0.0/0
                          gw: igw
        region: "{{ aws_region }}"
        wait: yes
  register: vpc

- name: write vpc id to vpc_info.yml file
  local_action: shell echo "{{ env }}"_vpc":" "{{ vpc.vpc_id }}"
                      > vars/"{{ env }}"/vpc_info.yml
- name: write subnets id to {{ prefix }}_vpc_info file
  local_action: shell echo "{{ item.resource_tags.Name }}"":" "{{ item.id }}"
                      >> vars/"{{ env }}"/vpc_info.yml
  with_items: vpc.subnets



- name: Provision EC2 security group
  local_action:
        module: ec2_group
        state: present
        name: "{{ security_group }}"
        description: "{{ security_group }}"
        vpc_id: "{{ vpc.vpc_id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip:  54.93.72.147/32
          - proto: all
            cidr_ip: 54.93.72.147/32
  register: aws_sg


- name: write ec2_group id to vpc_info.yml file
  local_action: shell echo security_group_id1":" "{{ aws_sg.group_id }}"
                      >> vars/"{{ env }}"/vpc_info.yml
